baseURL = 'https://trophy-wiki.github.io/ps3trophies/'
languageCode = 'ja-jp'
title = 'PS3トロフィーまとめWiki'

# disqusのID（使ってない）
disqusShortname = "https-ps3trophies-github-io"

# フロントマターで配列を扱う際のユーザー定義。デフォでcategoriesとtagsはある
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Web上でのページ編集に使う
[params]
  editBaseURL = "https://github.com/trophy-wiki/hugo_ps3trophies/edit/master/content"

# Markdown内でHTMLを直接書けるようになる
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Markdown内で任意のブロックにCSSを指定できるようになる
[markup.goldmark.parser.attribute]
block = true
