baseURL = 'https://ps3trophies.github.io'
languageCode = 'ja-jp'
title = 'PS3トロフィーまとめWiki'
disqusShortname = "https-ps3trophies-github-io"

# Web上でのページ編集に使う
[params]
  editBaseURL = "https://github.com/ps3trophies/hugo_ps3trophies/edit/master/content"

# Markdown内でHTMLを直接書けるようになる
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Markdown内で任意のブロックにCSSを指定できるようになる
[markup.goldmark.parser.attribute]
block = true